services:
  db:
    platform: linux/amd64
    image: timescale/timescaledb-postgis:2.2.1-pg13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./data/raw:/data/raw
    shm_size: 2gb                # shared memory size

volumes:
  pgdata: